modLoader = "kotlinforforge"
loaderVersion = "[1,)"
license = "MIT Code & ARR Assets"

[[mods]]
modId = "m4id"
version = "0.1.0-alpha.1"
displayName = "M4id"
description = "Fork of Kambrik, a Lightweight Kotlin-Fabric Library."
logoFile = ""
credits = "DoctorM4id"
authors = "DoctorM4id"
contact = ""